[package]
name = "ft-logic"
version = "0.1.0"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive", "full"] }
gstd = { git = "https://github.com/gear-tech/gear.git", features = ["debug"] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
ft-logic-io = { path = "io" }
ft-storage-io = { path = "../ft-storage/io" }
sp-core-hashing = { version = "4.0.0", default-features = false }
primitive-types = { version = "0.11.1", default-features = false, features = ["scale-info"]}
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git" }
gclient = { git = "https://github.com/gear-tech/gear.git" }
tokio = { version = "1.21.2", features = ["full"] }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git" }